### ISSUE TITLE
Nothing returned by articles API

### ISSUE THREAD

**Issue by Vallenain** [vpmalley/jetlag#51]
Unless #50 a call to `api/0.1/articles` does not return anything (empty array). I checked the db, there are some articles who are public and not drafts so I think they should be returned.

**Comment by vpmalley** [comment]
Actually the `GET api/0.1/articles` endpoint does not return ALL articles, but only the articles for the logged user. The reason is simply that returning public articles of other users would make the number of articles too big - or if we return a subset, how do we choose them?

I expect to create an endpoint like `GET api/0.1/articles/suggested` or `GET api/0.1/articles/curated` that would return a selection of [random|most popular|most recent] public and published articles of any user. Is that what you want? If so, update this issue as a new feature for such a selection of articles.

**Comment by Vallenain** [comment]
My bad, you're right. The endpoint used in the homepage (before a search is performed) should be a custom endpoint with our magical "suggestions" algorithm.
